'use client';

/**
 * DynamicPortfolioRenderer - Renders semantic blocks with design tokens.
 *
 * This component takes design tokens and semantic blocks generated by AI
 * and renders them as styled React elements. It maps design tokens to
 * Tailwind classes and handles all semantic block types.
 *
 * @see /src/lib/design/tokens.ts - Design token definitions
 * @see /src/lib/design/semantic-blocks.ts - Semantic block definitions
 * @see /docs/03-architecture/agentic-ui.md - Architecture documentation
 */

import { useState, useCallback } from 'react';
import {
  ChevronLeft,
  ChevronRight,
  Info,
  Lightbulb,
  AlertTriangle,
  Quote,
  ArrowRight,
  Share2,
  Mail,
} from 'lucide-react';
import { type DesignTokens, tokensToClasses, type ResolvedClasses } from '@/lib/design/tokens';
import type {
  SemanticBlock,
  ParagraphBlock,
  HeadingBlock,
  ListBlock,
  CalloutBlock,
  HeroSectionBlock,
  BeforeAfterBlock,
  FeatureCardBlock,
  ImageGalleryBlock,
  TestimonialBlock,
  CtaSectionBlock,
  StatsBlock,
  ProcessStepBlock,
  MaterialsListBlock,
  DividerBlock,
} from '@/lib/design/semantic-blocks';
import { SafeImage, Button, Card, CardContent } from '@/components/ui';
import { cn } from '@/lib/utils';

// =============================================================================
// Types
// =============================================================================

export interface PortfolioImage {
  id: string;
  url: string;
  alt?: string;
  width?: number;
  height?: number;
}

interface DynamicPortfolioRendererProps {
  tokens: DesignTokens;
  blocks: SemanticBlock[];
  images: PortfolioImage[];
  className?: string;
  /** Optional callback when CTA button is clicked */
  onCtaClick?: (action: 'contact' | 'view-more' | 'share') => void;
}

interface BlockRendererProps {
  block: SemanticBlock;
  classes: ResolvedClasses;
  getImageById: (id: string) => PortfolioImage | undefined;
  onCtaClick?: (action: 'contact' | 'view-more' | 'share') => void;
}

// Note: SafeImage component automatically provides shimmer placeholder via
// its default blurDataURL prop - no need to specify it on each usage.

// =============================================================================
// Main Component
// =============================================================================

/**
 * DynamicPortfolioRenderer renders semantic blocks using design tokens.
 *
 * @example
 * ```tsx
 * <DynamicPortfolioRenderer
 *   tokens={designTokens}
 *   blocks={semanticBlocks}
 *   images={projectImages}
 *   onCtaClick={(action) => console.log('CTA clicked:', action)}
 * />
 * ```
 */
export function DynamicPortfolioRenderer({
  tokens,
  blocks,
  images,
  className,
  onCtaClick,
}: DynamicPortfolioRendererProps) {
  const classes = tokensToClasses(tokens);

  const getImageById = useCallback(
    (id: string) => images.find((img) => img.id === id),
    [images]
  );

  if (!blocks || blocks.length === 0) {
    return null;
  }

  return (
    <article
      className={cn(
        'w-full',
        classes.layout.container,
        classes.spacing.container,
        classes.background.page,
        classes.background.text,
        className
      )}
    >
      {blocks.map((block, index) => (
        <BlockRenderer
          key={`${block.type}-${index}`}
          block={block}
          classes={classes}
          getImageById={getImageById}
          onCtaClick={onCtaClick}
        />
      ))}
    </article>
  );
}

// =============================================================================
// Block Router Component
// =============================================================================

function BlockRenderer({ block, classes, getImageById, onCtaClick }: BlockRendererProps) {
  switch (block.type) {
    case 'paragraph':
      return <ParagraphRenderer block={block} classes={classes} />;
    case 'heading':
      return <HeadingRenderer block={block} classes={classes} />;
    case 'list':
      return <ListRenderer block={block} classes={classes} />;
    case 'callout':
      return <CalloutRenderer block={block} classes={classes} />;
    case 'hero-section':
      return <HeroSectionRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'before-after':
      return <BeforeAfterRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'feature-card':
      return <FeatureCardRenderer block={block} classes={classes} />;
    case 'image-gallery':
      return <ImageGalleryRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'testimonial':
      return <TestimonialRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'cta-section':
      return <CtaSectionRenderer block={block} classes={classes} onCtaClick={onCtaClick} />;
    case 'stats':
      return <StatsRenderer block={block} classes={classes} />;
    case 'process-step':
      return <ProcessStepRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'materials-list':
      return <MaterialsListRenderer block={block} classes={classes} />;
    case 'divider':
      return <DividerRenderer block={block} />;
    default:
      // TypeScript exhaustive check
      return null;
  }
}

// =============================================================================
// Text Content Block Renderers
// =============================================================================

function ParagraphRenderer({
  block,
  classes,
}: {
  block: ParagraphBlock;
  classes: ResolvedClasses;
}) {
  return (
    <p className={cn(classes.body, classes.background.text, 'max-w-prose')}>
      {block.text}
    </p>
  );
}

function HeadingRenderer({
  block,
  classes,
}: {
  block: HeadingBlock;
  classes: ResolvedClasses;
}) {
  const baseClasses = cn(classes.heading, classes.background.text);

  if (block.level === '2') {
    return <h2 className={cn(baseClasses, 'text-2xl md:text-3xl mb-4')}>{block.text}</h2>;
  }

  return <h3 className={cn(baseClasses, 'text-xl md:text-2xl mb-3')}>{block.text}</h3>;
}

function ListRenderer({
  block,
  classes,
}: {
  block: ListBlock;
  classes: ResolvedClasses;
}) {
  const listClasses = cn(classes.body, classes.background.text, 'space-y-2 pl-6');

  if (block.style === 'number') {
    return (
      <ol className={cn(listClasses, 'list-decimal')}>
        {block.items.map((item, idx) => (
          <li key={idx}>{item}</li>
        ))}
      </ol>
    );
  }

  return (
    <ul className={cn(listClasses, 'list-disc')}>
      {block.items.map((item, idx) => (
        <li key={idx}>{item}</li>
      ))}
    </ul>
  );
}

function CalloutRenderer({
  block,
  classes,
}: {
  block: CalloutBlock;
  classes: ResolvedClasses;
}) {
  const variantStyles = {
    info: {
      container: 'border-blue-200 bg-blue-50 dark:border-blue-900 dark:bg-blue-950/50',
      icon: <Info className="h-5 w-5 text-blue-600 dark:text-blue-400 flex-shrink-0" />,
    },
    tip: {
      container: 'border-green-200 bg-green-50 dark:border-green-900 dark:bg-green-950/50',
      icon: <Lightbulb className="h-5 w-5 text-green-600 dark:text-green-400 flex-shrink-0" />,
    },
    warning: {
      container: 'border-amber-200 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/50',
      icon: <AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-400 flex-shrink-0" />,
    },
  };

  const style = variantStyles[block.variant];

  return (
    <div className={cn('rounded-lg border p-4 flex gap-3', style.container)}>
      {style.icon}
      <div className="flex-1">
        {block.title && (
          <h4 className={cn(classes.heading, 'text-base mb-1')}>{block.title}</h4>
        )}
        <p className={cn(classes.body, 'text-sm')}>{block.text}</p>
      </div>
    </div>
  );
}

// =============================================================================
// Layout-Aware Block Renderers
// =============================================================================

function HeroSectionRenderer({
  block,
  classes,
  getImageById,
}: {
  block: HeroSectionBlock;
  classes: ResolvedClasses;
  getImageById: (id: string) => PortfolioImage | undefined;
}) {
  const heroImages = block.imageIds
    .map((id) => getImageById(id))
    .filter((img): img is PortfolioImage => !!img);

  if (heroImages.length === 0) {
    return null;
  }

  // Render based on layout type
  const renderHeroLayout = () => {
    switch (block.layout) {
      case 'large-single': {
        const mainImage = heroImages[0];
        if (!mainImage) return null;
        return (
          <div className={cn(classes.hero.container, classes.image, 'relative')}>
            <SafeImage
              src={mainImage.url}
              alt={mainImage.alt || 'Hero image'}
              fill
              className="object-cover"
              sizes="(max-width: 768px) 100vw, 1200px"
              priority
            />
          </div>
        );
      }

      case 'grid': {
        const gridImages = heroImages.slice(0, 3);
        return (
          <div className={cn('grid grid-cols-3 gap-2', classes.spacing.gap)}>
            {gridImages.map((img, idx) => (
              <div
                key={img.id}
                className={cn('relative aspect-video', classes.image)}
              >
                <SafeImage
                  src={img.url}
                  alt={img.alt || `Hero image ${idx + 1}`}
                  fill
                  className="object-cover"
                  sizes="(max-width: 768px) 33vw, 400px"
                  priority={idx === 0}
                />
              </div>
            ))}
          </div>
        );
      }

      case 'side-by-side': {
        const leftImage = heroImages[0];
        const rightImage = heroImages[1] || heroImages[0];
        if (!leftImage) return null;
        return (
          <div className={cn('grid grid-cols-2 gap-4', classes.spacing.gap)}>
            <div className={cn('relative aspect-[4/3]', classes.image)}>
              <SafeImage
                src={leftImage.url}
                alt={leftImage.alt || 'Hero image left'}
                fill
                className="object-cover"
                sizes="(max-width: 768px) 50vw, 600px"
                priority
              />
            </div>
            <div className={cn('relative aspect-[4/3]', classes.image)}>
              <SafeImage
                src={rightImage?.url || ''}
                alt={rightImage?.alt || 'Hero image right'}
                fill
                className="object-cover"
                sizes="(max-width: 768px) 50vw, 600px"
              />
            </div>
          </div>
        );
      }

      default:
        return null;
    }
  };

  return (
    <section className={cn(classes.spacing.section, 'relative')}>
      {renderHeroLayout()}

      {/* Overlay title and subtitle */}
      {(block.title || block.subtitle) && (
        <div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black/70 to-transparent">
          {block.title && (
            <h1 className={cn(classes.heading, 'text-3xl md:text-4xl text-white mb-2')}>
              {block.title}
            </h1>
          )}
          {block.subtitle && (
            <p className="text-lg text-white/80">{block.subtitle}</p>
          )}
        </div>
      )}
    </section>
  );
}

function BeforeAfterRenderer({
  block,
  classes,
  getImageById,
}: {
  block: BeforeAfterBlock;
  classes: ResolvedClasses;
  getImageById: (id: string) => PortfolioImage | undefined;
}) {
  const [sliderPosition, setSliderPosition] = useState(50);
  const beforeImage = getImageById(block.beforeImageId);
  const afterImage = getImageById(block.afterImageId);

  if (!beforeImage || !afterImage) {
    return null;
  }

  return (
    <section className={classes.spacing.section}>
      <div className="relative aspect-video overflow-hidden rounded-lg">
        {/* After image (full) */}
        <div className={cn('absolute inset-0', classes.image)}>
          <SafeImage
            src={afterImage.url}
            alt={afterImage.alt || 'After'}
            fill
            className="object-cover"
            sizes="(max-width: 768px) 100vw, 896px"
          />
        </div>

        {/* Before image (clipped) */}
        <div
          className={cn('absolute inset-0 overflow-hidden', classes.image)}
          style={{ clipPath: `inset(0 ${100 - sliderPosition}% 0 0)` }}
        >
          <SafeImage
            src={beforeImage.url}
            alt={beforeImage.alt || 'Before'}
            fill
            className="object-cover"
            sizes="(max-width: 768px) 100vw, 896px"
          />
        </div>

        {/* Slider handle */}
        <div
          className="absolute top-0 bottom-0 w-1 bg-white cursor-ew-resize z-10"
          style={{ left: `${sliderPosition}%` }}
        >
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-10 h-10 bg-white rounded-full shadow-lg flex items-center justify-center">
            <ChevronLeft className="h-4 w-4 text-gray-600" />
            <ChevronRight className="h-4 w-4 text-gray-600" />
          </div>
        </div>

        {/* Slider input */}
        <input
          type="range"
          min={0}
          max={100}
          value={sliderPosition}
          onChange={(e) => setSliderPosition(Number(e.target.value))}
          className="absolute inset-0 w-full h-full opacity-0 cursor-ew-resize z-20"
          aria-label="Adjust before/after comparison"
        />

        {/* Labels */}
        <div className="absolute top-4 left-4 px-3 py-1 bg-black/70 text-white text-sm font-medium rounded">
          Before
        </div>
        <div className="absolute top-4 right-4 px-3 py-1 bg-black/70 text-white text-sm font-medium rounded">
          After
        </div>
      </div>

      {block.caption && (
        <p className={cn(classes.body, classes.background.muted, 'text-center mt-4')}>
          {block.caption}
        </p>
      )}
    </section>
  );
}

function FeatureCardRenderer({
  block,
  classes,
}: {
  block: FeatureCardBlock;
  classes: ResolvedClasses;
}) {
  const variantStyles = {
    default: classes.background.card,
    highlight: cn(classes.accent.bg, 'text-white'),
    subtle: 'bg-transparent border-0 shadow-none',
  };

  return (
    <Card className={cn(variantStyles[block.variant], 'transition-shadow hover:shadow-md')}>
      <CardContent className="pt-6">
        {block.icon && (
          <div className={cn('text-2xl mb-3', block.variant === 'highlight' ? '' : classes.accent.text)}>
            {/* Icon placeholder - could be enhanced with an icon library lookup */}
            <span role="img" aria-label={block.icon}>
              {getIconEmoji(block.icon)}
            </span>
          </div>
        )}
        <h4
          className={cn(
            classes.heading,
            'text-lg mb-2',
            block.variant === 'highlight' ? 'text-white' : ''
          )}
        >
          {block.title}
        </h4>
        <p
          className={cn(
            classes.body,
            'text-sm',
            block.variant === 'highlight' ? 'text-white/90' : classes.background.muted
          )}
        >
          {block.content}
        </p>
      </CardContent>
    </Card>
  );
}

function ImageGalleryRenderer({
  block,
  classes,
  getImageById,
}: {
  block: ImageGalleryBlock;
  classes: ResolvedClasses;
  getImageById: (id: string) => PortfolioImage | undefined;
}) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const galleryImages = block.imageIds
    .map((id) => getImageById(id))
    .filter((img): img is PortfolioImage => !!img);

  if (galleryImages.length === 0) {
    return null;
  }

  const layoutClasses = {
    'grid-2': 'grid grid-cols-2 gap-4',
    'grid-3': 'grid grid-cols-2 md:grid-cols-3 gap-4',
    masonry: 'columns-2 md:columns-3 gap-4 space-y-4',
    carousel: 'relative overflow-hidden',
  };

  if (block.layout === 'carousel') {
    const currentImage = galleryImages[currentIndex];
    if (!currentImage) return null;

    return (
      <section className={classes.spacing.section}>
        <div className="relative aspect-video rounded-lg overflow-hidden">
          <SafeImage
            src={currentImage.url}
            alt={currentImage.alt || 'Gallery image'}
            fill
            className="object-cover"
            sizes="(max-width: 768px) 100vw, 896px"
          />

          {galleryImages.length > 1 && (
            <>
              <button
                onClick={() => setCurrentIndex((prev) => (prev > 0 ? prev - 1 : galleryImages.length - 1))}
                className="absolute left-4 top-1/2 -translate-y-1/2 p-2 bg-black/50 text-white rounded-full hover:bg-black/70 transition-colors"
                aria-label="Previous image"
              >
                <ChevronLeft className="h-6 w-6" />
              </button>
              <button
                onClick={() => setCurrentIndex((prev) => (prev < galleryImages.length - 1 ? prev + 1 : 0))}
                className="absolute right-4 top-1/2 -translate-y-1/2 p-2 bg-black/50 text-white rounded-full hover:bg-black/70 transition-colors"
                aria-label="Next image"
              >
                <ChevronRight className="h-6 w-6" />
              </button>
              <div className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-2">
                {galleryImages.map((_, idx) => (
                  <button
                    key={idx}
                    onClick={() => setCurrentIndex(idx)}
                    className={cn(
                      'w-2 h-2 rounded-full transition-colors',
                      idx === currentIndex ? 'bg-white' : 'bg-white/50'
                    )}
                    aria-label={`Go to image ${idx + 1}`}
                  />
                ))}
              </div>
            </>
          )}
        </div>

        {block.captions?.[currentImage.id] && (
          <p className={cn(classes.body, classes.background.muted, 'text-center mt-4')}>
            {block.captions[currentImage.id]}
          </p>
        )}
      </section>
    );
  }

  // Grid or masonry layout
  return (
    <section className={cn(classes.spacing.section, layoutClasses[block.layout])}>
      {galleryImages.map((img) => (
        <div
          key={img.id}
          className={cn(
            'relative',
            classes.image,
            block.layout === 'masonry' ? 'break-inside-avoid mb-4' : 'aspect-square'
          )}
        >
          <SafeImage
            src={img.url}
            alt={img.alt || 'Gallery image'}
            fill={block.layout !== 'masonry'}
            width={block.layout === 'masonry' ? img.width || 400 : undefined}
            height={block.layout === 'masonry' ? img.height || 300 : undefined}
            className={cn(
              'object-cover',
              block.layout === 'masonry' ? 'w-full h-auto rounded-lg' : ''
            )}
            sizes="(max-width: 768px) 50vw, 300px"
          />
          {block.captions?.[img.id] && (
            <div className="absolute bottom-0 left-0 right-0 p-2 bg-black/60 text-white text-xs">
              {block.captions[img.id]}
            </div>
          )}
        </div>
      ))}
    </section>
  );
}

function TestimonialRenderer({
  block,
  classes,
  getImageById,
}: {
  block: TestimonialBlock;
  classes: ResolvedClasses;
  getImageById: (id: string) => PortfolioImage | undefined;
}) {
  const testimonialImage = block.imageId ? getImageById(block.imageId) : null;

  return (
    <section className={cn(classes.spacing.section, 'relative')}>
      <Card className={cn(classes.background.card, 'border-l-4', classes.accent.border)}>
        <CardContent className="pt-6 flex gap-6">
          {testimonialImage && (
            <div className="flex-shrink-0">
              <div className={cn('relative w-16 h-16 rounded-full overflow-hidden', classes.image)}>
                <SafeImage
                  src={testimonialImage.url}
                  alt={testimonialImage.alt || 'Testimonial'}
                  fill
                  className="object-cover"
                  sizes="64px"
                />
              </div>
            </div>
          )}
          <div className="flex-1">
            <Quote className={cn('h-8 w-8 mb-3', classes.accent.text, 'opacity-50')} />
            <blockquote className={cn(classes.body, 'italic mb-4')}>
              &ldquo;{block.quote}&rdquo;
            </blockquote>
            {block.attribution && (
              <cite className={cn(classes.body, classes.background.muted, 'not-italic font-medium')}>
                &mdash; {block.attribution}
              </cite>
            )}
          </div>
        </CardContent>
      </Card>
    </section>
  );
}

function CtaSectionRenderer({
  block,
  classes,
  onCtaClick,
}: {
  block: CtaSectionBlock;
  classes: ResolvedClasses;
  onCtaClick?: (action: 'contact' | 'view-more' | 'share') => void;
}) {
  const actionIcons = {
    contact: <Mail className="h-4 w-4" />,
    'view-more': <ArrowRight className="h-4 w-4" />,
    share: <Share2 className="h-4 w-4" />,
  };

  return (
    <section
      className={cn(
        classes.spacing.section,
        'text-center py-12 px-6 rounded-xl',
        classes.accent.bg
      )}
    >
      <h3 className={cn(classes.heading, 'text-2xl md:text-3xl text-white mb-4')}>
        {block.heading}
      </h3>
      {block.body && (
        <p className="text-white/90 mb-6 max-w-xl mx-auto">{block.body}</p>
      )}
      <Button
        size="lg"
        variant="secondary"
        onClick={() => onCtaClick?.(block.buttonAction)}
        className="gap-2"
      >
        {block.buttonText}
        {actionIcons[block.buttonAction]}
      </Button>
    </section>
  );
}

function StatsRenderer({
  block,
  classes,
}: {
  block: StatsBlock;
  classes: ResolvedClasses;
}) {
  const gridCols = block.items.length <= 2 ? 'grid-cols-2' : block.items.length === 3 ? 'grid-cols-3' : 'grid-cols-2 md:grid-cols-4';

  return (
    <section className={classes.spacing.section}>
      <div
        className={cn(
          'grid gap-4',
          gridCols,
          'p-6 rounded-lg',
          classes.background.card,
          'border'
        )}
      >
        {block.items.map((item, idx) => (
          <div key={idx} className="text-center">
            <div className={cn(classes.heading, 'text-2xl md:text-3xl', classes.accent.text)}>
              {item.value}
            </div>
            <div className={cn(classes.body, 'text-sm', classes.background.muted)}>
              {item.label}
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}

function ProcessStepRenderer({
  block,
  classes,
  getImageById,
}: {
  block: ProcessStepBlock;
  classes: ResolvedClasses;
  getImageById: (id: string) => PortfolioImage | undefined;
}) {
  const stepImage = block.imageId ? getImageById(block.imageId) : null;

  return (
    <section className={cn(classes.spacing.section, 'flex gap-6')}>
      {/* Step number */}
      <div
        className={cn(
          'flex-shrink-0 w-12 h-12 rounded-full flex items-center justify-center text-xl font-bold',
          classes.accent.bg,
          'text-white'
        )}
      >
        {block.stepNumber}
      </div>

      {/* Content */}
      <div className="flex-1">
        <h4 className={cn(classes.heading, 'text-lg mb-2')}>{block.title}</h4>
        <p className={cn(classes.body, classes.background.muted, 'mb-4')}>
          {block.content}
        </p>

        {stepImage && (
          <div className={cn('relative aspect-video rounded-lg overflow-hidden', classes.image)}>
            <SafeImage
              src={stepImage.url}
              alt={stepImage.alt || `Step ${block.stepNumber}`}
              fill
              className="object-cover"
              sizes="(max-width: 768px) 100vw, 600px"
            />
          </div>
        )}
      </div>
    </section>
  );
}

function MaterialsListRenderer({
  block,
  classes,
}: {
  block: MaterialsListBlock;
  classes: ResolvedClasses;
}) {
  return (
    <section className={classes.spacing.section}>
      <Card className={classes.background.card}>
        <CardContent className="pt-6">
          {block.title && (
            <h4 className={cn(classes.heading, 'text-lg mb-4 flex items-center gap-2')}>
              <span className={cn('w-2 h-2 rounded-full', classes.accent.bg)} />
              {block.title}
            </h4>
          )}
          <ul className="space-y-3">
            {block.items.map((item, idx) => (
              <li
                key={idx}
                className={cn(
                  'flex items-start gap-3',
                  classes.body,
                  classes.background.muted
                )}
              >
                <span className={cn('mt-1.5', classes.accent.text)}>&#8226;</span>
                <div>
                  <span className={cn('font-medium', classes.background.text)}>
                    {item.name}
                  </span>
                  {item.description && (
                    <span className="text-sm"> &mdash; {item.description}</span>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>
    </section>
  );
}

function DividerRenderer({ block }: { block: DividerBlock }) {
  const styleClasses = {
    line: 'border-t border-border',
    dots: 'flex items-center justify-center gap-2',
    space: 'h-8',
  };

  if (block.style === 'dots') {
    return (
      <div className={cn('py-6', styleClasses.dots)}>
        <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground/40" />
        <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground/40" />
        <span className="w-1.5 h-1.5 rounded-full bg-muted-foreground/40" />
      </div>
    );
  }

  return <hr className={cn('my-6', styleClasses[block.style || 'line'])} />;
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Maps icon names to emoji fallbacks.
 * In a production app, this could be replaced with a proper icon library.
 */
function getIconEmoji(iconName: string): string {
  const iconMap: Record<string, string> = {
    brick: '\ud83e\uddf1',
    tools: '\ud83d\udee0\ufe0f',
    clock: '\u23f0',
    hammer: '\ud83d\udd28',
    wrench: '\ud83d\udd27',
    home: '\ud83c\udfe0',
    building: '\ud83c\udfe2',
    check: '\u2705',
    star: '\u2b50',
    fire: '\ud83d\udd25',
    stone: '\ud83e\udea8',
    water: '\ud83d\udca7',
    shield: '\ud83d\udee1\ufe0f',
    award: '\ud83c\udfc6',
    calendar: '\ud83d\udcc5',
    location: '\ud83d\udccd',
    phone: '\ud83d\udcde',
    email: '\ud83d\udce7',
  };

  return iconMap[iconName.toLowerCase()] || '\ud83d\udccc';
}

export default DynamicPortfolioRenderer;
