'use client';

/**
 * DynamicPortfolioRenderer - Renders semantic blocks with design tokens.
 *
 * This component takes design tokens and semantic blocks generated by AI
 * and renders them as styled React elements. It maps design tokens to
 * Tailwind classes and handles all semantic block types.
 *
 * @see /src/lib/design/tokens.ts - Design token definitions
 * @see /src/lib/design/semantic-blocks.ts - Semantic block definitions
 * @see /docs/03-architecture/agentic-ui.md - Architecture documentation
 */

import { useCallback } from 'react';
import { type DesignTokens, tokensToClasses, type ResolvedClasses } from '@/lib/design/tokens';
import type { SemanticBlock } from '@/lib/design/semantic-blocks';
import { cn } from '@/lib/utils';
import type { PortfolioCtaAction, PortfolioImage } from './types';
import { CalloutRenderer } from './blocks/callout-block';
import { DividerRenderer } from './blocks/divider-block';
import {
  BeforeAfterRenderer,
  HeroSectionRenderer,
  ImageGalleryRenderer,
  ProcessStepRenderer,
  TestimonialRenderer,
} from './blocks/media-blocks';
import {
  CtaSectionRenderer,
  FeatureCardRenderer,
  MaterialsListRenderer,
  StatsRenderer,
} from './blocks/card-blocks';
import { HeadingRenderer, ListRenderer, ParagraphRenderer } from './blocks/text-blocks';

// =============================================================================
// Types
// =============================================================================

interface DynamicPortfolioRendererProps {
  tokens: DesignTokens;
  blocks: SemanticBlock[];
  images: PortfolioImage[];
  className?: string;
  /** Optional callback when CTA button is clicked */
  onCtaClick?: (action: PortfolioCtaAction) => void;
}

interface BlockRendererProps {
  block: SemanticBlock;
  classes: ResolvedClasses;
  getImageById: (id: string) => PortfolioImage | undefined;
  onCtaClick?: (action: PortfolioCtaAction) => void;
}

// Note: SafeImage component automatically provides shimmer placeholder via
// its default blurDataURL prop - no need to specify it on each usage.

// =============================================================================
// Main Component
// =============================================================================

/**
 * DynamicPortfolioRenderer renders semantic blocks using design tokens.
 *
 * @example
 * ```tsx
 * <DynamicPortfolioRenderer
 *   tokens={designTokens}
 *   blocks={semanticBlocks}
 *   images={projectImages}
 *   onCtaClick={(action) => console.log('CTA clicked:', action)}
 * />
 * ```
 */
export function DynamicPortfolioRenderer({
  tokens,
  blocks,
  images,
  className,
  onCtaClick,
}: DynamicPortfolioRendererProps) {
  const classes = tokensToClasses(tokens);

  const getImageById = useCallback(
    (id: string) => images.find((img) => img.id === id),
    [images]
  );

  if (!blocks || blocks.length === 0) {
    return null;
  }

  return (
    <article
      className={cn(
        'w-full',
        classes.layout.container,
        classes.spacing.container,
        classes.background.page,
        classes.background.text,
        className
      )}
    >
      {blocks.map((block, index) => (
        <BlockRenderer
          key={`${block.type}-${index}`}
          block={block}
          classes={classes}
          getImageById={getImageById}
          onCtaClick={onCtaClick}
        />
      ))}
    </article>
  );
}

// =============================================================================
// Block Router Component
// =============================================================================

function BlockRenderer({ block, classes, getImageById, onCtaClick }: BlockRendererProps) {
  switch (block.type) {
    case 'paragraph':
      return <ParagraphRenderer block={block} classes={classes} />;
    case 'heading':
      return <HeadingRenderer block={block} classes={classes} />;
    case 'list':
      return <ListRenderer block={block} classes={classes} />;
    case 'callout':
      return <CalloutRenderer block={block} classes={classes} />;
    case 'hero-section':
      return <HeroSectionRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'before-after':
      return <BeforeAfterRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'feature-card':
      return <FeatureCardRenderer block={block} classes={classes} />;
    case 'image-gallery':
      return <ImageGalleryRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'testimonial':
      return <TestimonialRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'cta-section':
      return <CtaSectionRenderer block={block} classes={classes} onCtaClick={onCtaClick} />;
    case 'stats':
      return <StatsRenderer block={block} classes={classes} />;
    case 'process-step':
      return <ProcessStepRenderer block={block} classes={classes} getImageById={getImageById} />;
    case 'materials-list':
      return <MaterialsListRenderer block={block} classes={classes} />;
    case 'divider':
      return <DividerRenderer block={block} />;
    default:
      return null;
  }
}

export default DynamicPortfolioRenderer;
