/**
 * Type definitions for review-agent-dashboard
 *
 * These types mirror the database schema used by contractor-review-agent
 * and add dashboard-specific types for UI state and filtering.
 *
 * @see contractor-review-agent/src/lib/types.ts for original definitions
 */

// =============================================================================
// Database Types (from Supabase tables)
// =============================================================================

/**
 * Contractor record from review_contractors table
 */
export interface DBContractor {
  id: string;
  place_id: string;
  cid: string | null;
  business_name: string;
  /** Google Maps business categories (array). Source: DataForSEO API. */
  category: string[];
  city: string;
  state: string | null;
  country: string;
  rating: number | null;
  review_count: number | null;
  address: string | null;
  phone: string | null;
  website: string | null;
  latitude: number | null;
  longitude: number | null;
  is_claimed: boolean;
  discovered_at: string;
  last_synced_at: string;
  /** Discovery search terms that found this contractor (e.g., "masonry contractors denver"). */
  search_terms: string[];
}

/**
 * Review record from review_data table
 */
export interface DBReview {
  id: string;
  contractor_id: string;
  review_id: string | null;
  review_text: string | null;
  rating: number;
  reviewer_name: string | null;
  review_date: string | null;
  owner_response: string | null;
  fetched_at: string;
  /** AI-generated analysis of this individual review (from tag-reviews.ts) */
  analysis_json?: ReviewTagAnalysis | null;
}

/**
 * AI analysis record from review_analysis table
 */
export interface DBAnalysis {
  id: string;
  contractor_id: string;
  analysis_json: ReviewAnalysis;
  model_used?: string;
  tokens_used?: number;
  cost_estimate?: number;
  analyzed_at: string;
}

/**
 * Generated article from review_articles table
 */
export interface DBArticle {
  id: string;
  contractor_id: string;
  title: string;
  slug: string;
  content_markdown: string;
  metadata_json: ArticleMetadata;
  model_used?: string;
  tokens_used?: number;
  cost_estimate?: number;
  status: 'draft' | 'published';
  generated_at: string;
}

// =============================================================================
// Analysis Types
// =============================================================================

/**
 * Structured analysis of contractor reviews
 * Generated by AI during the analysis phase
 */
export interface ReviewAnalysis {
  summary: {
    total_reviews: number;
    average_rating: number;
    rating_distribution: Record<string, number>; // "5": 45, "4": 20, etc.
  };
  sentiment: {
    overall: 'positive' | 'negative' | 'mixed' | 'neutral';
    score: number; // -1 to 1
  };
  themes: {
    positive: ThemeAnalysis[];
    negative: ThemeAnalysis[];
  };
  notable_quotes: NotableQuote[];
  red_flags: string[];
  strengths: string[];
  recommendations: string[];
}

export interface ThemeAnalysis {
  theme: string;
  count: number;
  examples: string[];
}

export interface NotableQuote {
  quote: string;
  rating: number;
  context: string;
  sentiment: 'positive' | 'negative' | 'neutral';
}

/**
 * Individual review analysis result (stored in review_data.analysis_json)
 * Generated by tag-reviews.ts script using Gemini
 *
 * @see contractor-review-agent/src/lib/gemini.ts for the original definition
 */
export interface ReviewTagAnalysis {
  /** Services detected in the review (open-ended, inferred from context) */
  detected_services: string[];
  /** Overall sentiment of the review */
  sentiment: 'positive' | 'negative' | 'neutral' | 'mixed';
  /** Sentiment score from -1 (very negative) to 1 (very positive) */
  sentiment_score: number;
  /** Themes the review discusses (e.g., "quality work", "on time") */
  themes: string[];
  /** Notable phrases extracted from the review */
  key_phrases: string[];
  /** Type of project mentioned */
  project_type: 'repair' | 'new_construction' | 'maintenance' | 'consultation' | null;
  /** Whether the review mentions pricing */
  mentions_price: boolean;
  /** Whether the review mentions timelines */
  mentions_timeline: boolean;
  /** Confidence in the analysis (0-1) */
  confidence: number;
}

// =============================================================================
// Article Types
// =============================================================================

/**
 * Metadata for generated articles
 */
export interface ArticleMetadata {
  seo: {
    title: string;
    description: string;
    keywords: string[];
  };
  structured_data: {
    type: 'LocalBusiness';
    name: string;
    aggregateRating: {
      ratingValue: number;
      reviewCount: number;
    };
  };
  generated_with: {
    model: string;
    timestamp: string;
    review_count: number;
  };
}

// =============================================================================
// Dashboard-Specific Types
// =============================================================================

/**
 * Pipeline statistics for dashboard overview
 */
export interface PipelineStats {
  contractors: number;
  reviews: number;
  analyses: number;
  articles: number;
  analysisRate: number; // percentage of contractors with analysis
  articleRate: number; // percentage of contractors with articles
}

/**
 * Contractor with computed status fields for dashboard display
 */
export interface ContractorWithStatus extends DBContractor {
  reviewCount: number;
  hasAnalysis: boolean;
  hasArticle: boolean;
}

/**
 * Filter options for contractor list
 */
export interface ContractorFilters {
  location?: string;
  category?: string;
  searchTerm?: string;
  minRating?: number;
  maxRating?: number;
  hasReviews?: boolean;
  hasAnalysis?: boolean;
  hasArticle?: boolean;
  search?: string;
}

/**
 * Sort options for articles list
 */
export type ArticleSortOption =
  | 'generated_desc'
  | 'generated_asc'
  | 'title_asc'
  | 'title_desc'
  | 'contractor_asc'
  | 'contractor_desc';

/**
 * Filter options for articles list
 */
export interface ArticleFilters {
  status?: 'draft' | 'published';
  search?: string;
  sort?: ArticleSortOption;
}

/**
 * Pagination parameters
 */
export interface Pagination {
  page: number;
  limit: number;
  total: number;
}

/**
 * Paginated response wrapper
 */
export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

/**
 * Article with associated contractor data
 */
export interface ArticleWithContractor extends DBArticle {
  contractor: DBContractor;
}

/**
 * Analysis with associated contractor data
 */
export interface AnalysisWithContractor extends DBAnalysis {
  contractor: DBContractor;
}

/**
 * Recent activity summary for dashboard
 */
export interface RecentActivity {
  recentContractors: DBContractor[];
  recentAnalyses: AnalysisWithContractor[];
  recentArticles: ArticleWithContractor[];
}

/**
 * Full contractor detail including all related data
 */
export interface ContractorDetail extends DBContractor {
  reviews: DBReview[];
  analysis: DBAnalysis | null;
  article: DBArticle | null;
}

// =============================================================================
// Observability Types (AI Usage Logs, Search History, Cost Tracking)
// =============================================================================

/**
 * AI usage log entry from ai_usage_log table
 * Tracks Gemini API calls for cost analysis
 */
export interface AIUsageLog {
  id: string;
  operation: 'analyze' | 'generate' | 'discover';
  contractor_id: string | null;
  model: string;
  input_tokens: number | null;
  output_tokens: number | null;
  total_tokens: number;
  cost_estimate: number;
  duration_ms: number | null;
  success: boolean;
  error_message: string | null;
  created_at: string;
}

/**
 * AI usage log with associated contractor data
 */
export interface AIUsageLogWithContractor extends AIUsageLog {
  contractor: DBContractor | null;
}

/**
 * Searched city record from searched_cities table
 * Tracks discovery searches to prevent duplicates
 */
export interface SearchedCity {
  id: string;
  city: string;
  state: string | null;
  country: string;
  search_term: string;
  contractors_found: number;
  searched_at: string;
}

/**
 * Aggregated AI usage statistics
 */
export interface AIUsageStats {
  totalOperations: number;
  totalTokens: number;
  totalInputTokens: number;
  totalOutputTokens: number;
  totalCost: number;
  avgCostPerOperation: number;
  avgTokensPerOperation: number;
  byOperation: {
    analyze: { count: number; tokens: number; inputTokens: number; outputTokens: number; cost: number };
    generate: { count: number; tokens: number; inputTokens: number; outputTokens: number; cost: number };
    discover: { count: number; tokens: number; inputTokens: number; outputTokens: number; cost: number };
  };
  successRate: number;
}

/**
 * Daily cost trend data point
 */
export interface DailyCostTrend {
  date: string;
  cost: number;
  tokens: number;
  operations: number;
}

/**
 * Model performance statistics
 */
export interface ModelStats {
  model: string;
  totalOperations: number;
  totalTokens: number;
  totalCost: number;
  avgDuration: number;
  successRate: number;
}

/**
 * Filter options for AI usage logs
 */
export interface AIUsageFilters {
  operation?: 'analyze' | 'generate' | 'discover';
  success?: boolean;
  since?: string; // ISO date string
  until?: string; // ISO date string
}

/**
 * Filter options for search history
 */
export interface SearchHistoryFilters {
  city?: string;
  state?: string;
  searchTerm?: string;
}

/**
 * Pipeline timing data (real, not placeholder)
 */
export interface PipelineTimingStats {
  discover: {
    avgDuration: number | null;
    lastRun: string | null;
    totalRuns: number;
  };
  analyze: {
    avgDuration: number | null;
    lastRun: string | null;
    totalRuns: number;
  };
  generate: {
    avgDuration: number | null;
    lastRun: string | null;
    totalRuns: number;
  };
}
