/**
 * MediaGridView Component for Payload Admin
 *
 * A visual grid view component for browsing media files in the Payload admin.
 * Displays thumbnails with hover overlays showing filename and metadata.
 *
 * Design features:
 * - Responsive CSS Grid (3 cols desktop, 2 tablet, 1 mobile)
 * - Consistent aspect-ratio squares for uniform appearance
 * - Hover overlay with filename and file size
 * - Click navigates to media detail page
 * - Empty state with helpful message
 * - Dark mode support via Payload theme detection
 *
 * @example
 * ```tsx
 * // Intended for registration as a custom view in Media collection
 * // See Payload docs: https://payloadcms.com/docs/admin/views
 *
 * <MediaGridView items={mediaItems} baseUrl="/admin/collections/media" />
 * ```
 *
 * @see Media.ts for collection configuration
 * @see StatusBadge.tsx for similar styling patterns
 * @see https://payloadcms.com/docs/admin/views#collection-views
 */
'use client'

import React, { useState, useEffect } from 'react'

/**
 * Media item shape matching Payload's Media collection
 * Subset of fields needed for grid display
 */
export interface MediaItem {
  id: string
  filename: string
  alt?: string
  mimeType?: string
  filesize?: number
  width?: number
  height?: number
  url?: string
  /** Thumbnail size generated by Payload */
  sizes?: {
    thumbnail?: {
      url?: string
      width?: number
      height?: number
    }
    card?: {
      url?: string
      width?: number
      height?: number
    }
  }
  updatedAt?: string
}

export interface MediaGridViewProps {
  /** Array of media items to display */
  items: MediaItem[]
  /** Base URL for media detail links (default: '/admin/collections/media') */
  baseUrl?: string
  /** Optional additional className for container */
  className?: string
}

/**
 * Format file size in human-readable form
 * @param bytes - File size in bytes
 * @returns Formatted string (e.g., "1.2 MB", "256 KB")
 */
const formatFileSize = (bytes: number | undefined): string => {
  if (!bytes) return ''

  const units = ['B', 'KB', 'MB', 'GB']
  let size = bytes
  let unitIndex = 0

  while (size >= 1024 && unitIndex < units.length - 1) {
    size /= 1024
    unitIndex++
  }

  return `${size.toFixed(unitIndex > 0 ? 1 : 0)} ${units[unitIndex]}`
}

/**
 * Check if mime type represents an image
 */
const isImage = (mimeType?: string): boolean => {
  return Boolean(mimeType?.startsWith('image/'))
}

/**
 * Single media thumbnail card component
 */
const MediaThumbnail: React.FC<{
  item: MediaItem
  baseUrl: string
  isDark: boolean
}> = ({ item, baseUrl, isDark }) => {
  const [isHovered, setIsHovered] = useState(false)

  // Use thumbnail size if available, fall back to card, then full URL
  const thumbnailUrl =
    item.sizes?.thumbnail?.url || item.sizes?.card?.url || item.url

  const containerStyle: React.CSSProperties = {
    position: 'relative',
    aspectRatio: '1 / 1',
    borderRadius: 'var(--style-radius-m, 8px)',
    overflow: 'hidden',
    cursor: 'pointer',
    backgroundColor: isDark
      ? 'hsl(260, 5%, 18%)'
      : 'hsl(0, 0%, 96%)',
    border: `1px solid ${
      isDark
        ? 'hsl(260, 3%, 25%)'
        : 'hsl(0, 0%, 90%)'
    }`,
    transition: 'all 0.2s ease',
    transform: isHovered ? 'translateY(-2px)' : 'translateY(0)',
    boxShadow: isHovered
      ? isDark
        ? '0 8px 24px rgba(0, 0, 0, 0.4)'
        : '0 8px 24px rgba(0, 0, 0, 0.12)'
      : '0 1px 3px rgba(0, 0, 0, 0.05)',
  }

  const imageStyle: React.CSSProperties = {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  }

  const placeholderStyle: React.CSSProperties = {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: isDark ? 'hsl(260, 5%, 50%)' : 'hsl(0, 0%, 60%)',
    fontSize: '2rem',
  }

  const overlayStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: isDark
      ? 'linear-gradient(to top, rgba(0, 0, 0, 0.85) 0%, rgba(0, 0, 0, 0) 50%)'
      : 'linear-gradient(to top, rgba(0, 0, 0, 0.75) 0%, rgba(0, 0, 0, 0) 50%)',
    opacity: isHovered ? 1 : 0,
    transition: 'opacity 0.2s ease',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    padding: '0.75rem',
  }

  const filenameStyle: React.CSSProperties = {
    color: 'white',
    fontSize: '0.75rem',
    fontWeight: 600,
    lineHeight: 1.3,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    margin: 0,
  }

  const metaStyle: React.CSSProperties = {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: '0.65rem',
    marginTop: '2px',
    display: 'flex',
    gap: '0.5rem',
  }

  // File type icon for non-images
  const fileTypeIcon = () => {
    if (item.mimeType?.includes('pdf')) return '📄'
    if (item.mimeType?.includes('svg')) return '🎨'
    return '📎'
  }

  return (
    <a
      href={`${baseUrl}/${item.id}`}
      style={containerStyle}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      {isImage(item.mimeType) && thumbnailUrl ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={thumbnailUrl}
          alt={item.alt || item.filename}
          style={imageStyle}
          loading="lazy"
        />
      ) : (
        <div style={placeholderStyle}>{fileTypeIcon()}</div>
      )}

      <div style={overlayStyle}>
        <p style={filenameStyle}>{item.filename}</p>
        <div style={metaStyle}>
          {item.filesize && <span>{formatFileSize(item.filesize)}</span>}
          {item.width && item.height && (
            <span>
              {item.width}×{item.height}
            </span>
          )}
        </div>
      </div>
    </a>
  )
}

/**
 * Empty state component when no media items exist
 */
const EmptyState: React.FC<{ isDark: boolean }> = ({ isDark }) => {
  const containerStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4rem 2rem',
    textAlign: 'center',
    backgroundColor: isDark
      ? 'hsl(260, 5%, 14%)'
      : 'hsl(0, 0%, 98%)',
    borderRadius: 'var(--style-radius-l, 12px)',
    border: `1px dashed ${
      isDark ? 'hsl(260, 5%, 25%)' : 'hsl(0, 0%, 85%)'
    }`,
  }

  const iconStyle: React.CSSProperties = {
    fontSize: '3rem',
    marginBottom: '1rem',
    opacity: 0.6,
  }

  const titleStyle: React.CSSProperties = {
    fontSize: '1.125rem',
    fontWeight: 600,
    color: isDark ? 'hsl(260, 5%, 85%)' : 'hsl(0, 0%, 20%)',
    margin: '0 0 0.5rem 0',
  }

  const descStyle: React.CSSProperties = {
    fontSize: '0.875rem',
    color: isDark ? 'hsl(260, 5%, 55%)' : 'hsl(0, 0%, 50%)',
    margin: 0,
    maxWidth: '300px',
  }

  return (
    <div style={containerStyle}>
      <div style={iconStyle}>🖼️</div>
      <h3 style={titleStyle}>No media files yet</h3>
      <p style={descStyle}>
        Upload images or documents to see them displayed here in a grid view.
      </p>
    </div>
  )
}

/**
 * MediaGridView Component
 *
 * Displays media items in a responsive thumbnail grid.
 * Automatically adapts to light/dark theme via CSS media query detection.
 */
export const MediaGridView: React.FC<MediaGridViewProps> = ({
  items,
  baseUrl = '/admin/collections/media',
  className,
}) => {
  const [isDark, setIsDark] = useState(false)

  useEffect(() => {
    // Check for Payload's dark theme attribute
    const checkTheme = () => {
      const isDarkTheme =
        document.documentElement.getAttribute('data-theme') === 'dark'
      setIsDark(isDarkTheme)
    }

    checkTheme()

    // Observer for theme changes
    const observer = new MutationObserver(checkTheme)
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['data-theme'],
    })

    return () => observer.disconnect()
  }, [])

  const gridStyle: React.CSSProperties = {
    display: 'grid',
    // Responsive: 1 col mobile, 2 cols tablet (600px+), 3 cols desktop (900px+)
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '1rem',
    padding: '1rem 0',
  }

  // Handle empty state
  if (!items || items.length === 0) {
    return <EmptyState isDark={isDark} />
  }

  return (
    <div style={gridStyle} className={className}>
      {items.map((item) => (
        <MediaThumbnail
          key={item.id}
          item={item}
          baseUrl={baseUrl}
          isDark={isDark}
        />
      ))}
    </div>
  )
}

export default MediaGridView
