import { listExportFiles, readExportFile, type SerializedExportFile } from '@/lib/exports/reader'
import ExportViewer from '@/components/exports/ExportViewer'
import { PageHeader } from '@/components/dashboard/PageHeader'
import { FileJson, FolderOpen, Terminal, Download } from 'lucide-react'

/**
 * Exports Viewer Page (Server Component)
 *
 * Fetches real export files from the contractor-review-agent output directory.
 * Uses CONTRACTOR_REVIEW_AGENT_OUTPUT_DIR environment variable.
 *
 * Design: Mission Control dark theme with terminal/code aesthetic
 * - File cards with terminal-style filename display
 * - Tabs for viewing different data sections
 * - Working download functionality
 *
 * @see /Users/aaronbaker/knearme-workspace/review-agent-dashboard/src/lib/exports/reader.ts
 */

export const dynamic = 'force-dynamic'

export default async function ExportsPage() {
  // Fetch real export files from disk
  const files = await listExportFiles()

  // Pre-load the first export's data for immediate display
  let initialData = null
  if (files.length > 0) {
    initialData = await readExportFile(files[0].filename)
  }

  // Serialize dates for client component (Next.js can't serialize Date objects)
  const serializedFiles: SerializedExportFile[] = files.map((file) => ({
    ...file,
    timestamp: file.timestamp.toISOString(),
  }))

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <PageHeader
        title="Exports"
        subtitle="View and download JSON exports from the review agent"
        icon={Download}
        badge="Data"
        badgeColor="violet"
        recordCount={files.length}
      />

      {files.length === 0 ? (
        /* Empty state - Mission Control styling */
        <div className="rounded-lg bg-zinc-900/30 border border-zinc-800/50 p-12 text-center">
          <div className="inline-flex items-center justify-center h-16 w-16 rounded-full bg-zinc-800/50 border border-zinc-700/50 mb-4">
            <FolderOpen className="h-8 w-8 text-zinc-600" />
          </div>
          <h3 className="text-lg font-semibold text-zinc-300 mb-1">
            No exports found
          </h3>
          <p className="text-sm text-zinc-500 max-w-md mx-auto mb-6">
            Export files will appear here when generated by the contractor-review-agent.
          </p>

          {/* Setup instructions - Terminal style */}
          <div className="mt-6 rounded-lg bg-[#0d1117] border border-zinc-700/50 p-4 max-w-lg mx-auto text-left">
            <div className="flex items-center gap-2 mb-3 pb-3 border-b border-zinc-700/50">
              <div className="flex gap-1.5">
                <div className="w-3 h-3 rounded-full bg-[#ff5f56]" />
                <div className="w-3 h-3 rounded-full bg-[#ffbd2e]" />
                <div className="w-3 h-3 rounded-full bg-[#27c93f]" />
              </div>
              <Terminal className="h-3 w-3 text-zinc-500 ml-2" />
              <span className="text-xs text-zinc-500 font-mono">
                Generate exports
              </span>
            </div>
            <div className="space-y-2 text-xs font-mono">
              <div className="flex items-start gap-3">
                <span className="text-zinc-600 select-none w-4">1.</span>
                <code className="text-zinc-300">
                  <span className="text-cyan-400">cd</span> contractor-review-agent
                </code>
              </div>
              <div className="flex items-start gap-3">
                <span className="text-zinc-600 select-none w-4">2.</span>
                <code className="text-zinc-300">
                  <span className="text-cyan-400">npm run</span> sync -- --export
                </code>
              </div>
            </div>
          </div>

          {/* Environment variable hint */}
          <div className="mt-6 flex items-center justify-center gap-2 text-xs text-zinc-600">
            <FileJson className="h-3 w-3" />
            <span>Looking in:</span>
            <code className="px-2 py-1 rounded bg-zinc-800/50 border border-zinc-700/50 font-mono text-[10px] text-zinc-400">
              {process.env.CONTRACTOR_REVIEW_AGENT_OUTPUT_DIR ||
                '../contractor-review-agent/output'}
            </code>
          </div>
        </div>
      ) : (
        <ExportViewer
          files={serializedFiles}
          initialData={initialData}
        />
      )}
    </div>
  )
}
