/**
 * Type definitions for contractor-review-agent
 *
 * These types define the data structures used throughout the agent,
 * from DataForSEO API responses to Supabase storage.
 */

// =============================================================================
// DataForSEO Types
// =============================================================================

export interface DataForSEOCredentials {
  login: string;
  password: string;
}

export interface TaskMeta {
  status_code?: number;
  status_message?: string;
}

/**
 * Result from Google Maps search - basic contractor info
 * @see https://docs.dataforseo.com/v3/serp/google/maps/live/advanced/
 */
export interface GoogleMapsResult {
  title: string;
  place_id: string | null;
  cid: string | null;
  address: string | null;
  phone: string | null;
  website: string | null;
  rating: number | null;
  reviews_count: number | null;
  category: string | null;
  position: number;
  latitude: number | null;
  longitude: number | null;
  is_claimed: boolean;
  work_hours: Record<string, string> | null;
}

/**
 * Individual review from Google Reviews API
 * @see https://docs.dataforseo.com/v3/business_data/google/reviews/task_get/
 */
export interface GoogleReview {
  review_id: string | null;
  review_text: string | null;
  original_review_text: string | null;
  rating: number;
  reviewer_name: string | null;
  reviewer_url: string | null;
  review_url: string | null;
  time_ago: string | null;
  timestamp: string | null;
  owner_response: string | null;
  owner_response_timestamp: string | null;
  review_images: string[] | null;
}

/**
 * Result from Google Reviews API
 */
export interface GoogleReviewsResult {
  place_id: string;
  cid: string | null;
  reviews: GoogleReview[];
  rating: number | null;
  reviews_count: number | null;
}

// =============================================================================
// Supabase / Database Types
// =============================================================================

/**
 * Contractor record as stored in Supabase
 */
export interface DBContractor {
  id: string;
  place_id: string;
  cid: string | null;
  business_name: string;
  /** Google Maps business categories (array). Source: DataForSEO API. */
  category: string[];
  city: string;
  state: string | null;
  country: string;
  rating: number | null;
  review_count: number | null;
  address: string | null;
  phone: string | null;
  website: string | null;
  latitude: number | null;
  longitude: number | null;
  is_claimed: boolean;
  discovered_at: string;
  last_synced_at: string;
  /** Discovery search terms that found this contractor (e.g., "masonry contractors denver"). */
  search_terms: string[];
}

/**
 * Review record as stored in Supabase
 */
export interface DBReview {
  id: string;
  contractor_id: string;
  review_id: string | null;
  review_text: string | null;
  rating: number;
  reviewer_name: string | null;
  review_date: string | null;
  owner_response: string | null;
  fetched_at: string;
}

/**
 * AI analysis result as stored in Supabase
 */
export interface DBAnalysis {
  id: string;
  contractor_id: string;
  analysis_json: ReviewAnalysis;
  model_used?: string;      // e.g., "gemini-3-flash-preview"
  tokens_used?: number;     // For cost tracking
  analyzed_at: string;
}

/**
 * Generated article as stored in Supabase
 */
export interface DBArticle {
  id: string;
  contractor_id: string;
  title: string;
  slug: string;
  content_markdown: string;
  metadata_json: ArticleMetadata;
  model_used?: string;      // e.g., "gemini-3-flash-preview"
  tokens_used?: number;     // For cost tracking
  status: 'draft' | 'published';
  generated_at: string;
}

// =============================================================================
// Analysis Types
// =============================================================================

/**
 * Structured analysis of contractor reviews
 * Generated by Claude during the analysis phase
 */
export interface ReviewAnalysis {
  summary: {
    total_reviews: number;
    average_rating: number;
    rating_distribution: Record<string, number>; // "5": 45, "4": 20, etc.
  };
  sentiment: {
    overall: 'positive' | 'negative' | 'mixed' | 'neutral';
    score: number; // -1 to 1
  };
  themes: {
    positive: ThemeAnalysis[];
    negative: ThemeAnalysis[];
  };
  notable_quotes: NotableQuote[];
  red_flags: string[];
  strengths: string[];
  recommendations: string[];
}

export interface ThemeAnalysis {
  theme: string;
  count: number;
  examples: string[];
}

export interface NotableQuote {
  quote: string;
  rating: number;
  context: string;
  sentiment: 'positive' | 'negative' | 'neutral';
}

// =============================================================================
// Article Types
// =============================================================================

/**
 * Metadata for generated articles
 */
export interface ArticleMetadata {
  seo: {
    title: string;
    description: string;
    keywords: string[];
  };
  structured_data: {
    type: 'LocalBusiness';
    name: string;
    aggregateRating: {
      ratingValue: number;
      reviewCount: number;
    };
  };
  generated_with: {
    model: string;
    timestamp: string;
    review_count: number;
  };
}

// =============================================================================
// CLI / Pipeline Types
// =============================================================================

export interface DiscoverOptions {
  search: string;
  city: string;
  state?: string;
  country?: string;
  limit?: number;
  minRating?: number;
  minReviews?: number;
}

export interface CollectOptions {
  contractorId?: string;
  placeId?: string;
  maxReviews?: number;
}

export interface PipelineOptions {
  search: string;
  city: string;
  state?: string;
  country?: string;
  limit?: number;
  minRating?: number;
  minReviews?: number;
  maxReviewsPerContractor?: number;
  skipAnalysis?: boolean;
  skipArticles?: boolean;
}

export interface PipelineResult {
  discovered: number;
  reviewsCollected: number;
  analyzed: number;
  articlesGenerated: number;
  errors: string[];
}

// =============================================================================
// Location Mapping
// =============================================================================

/**
 * US state codes to DataForSEO location codes
 * Add more as needed
 */
export const US_LOCATION_CODES: Record<string, number> = {
  // National
  'us': 2840,
  'usa': 2840,
  'united states': 2840,

  // Major cities (add more as needed)
  'denver': 1014395,
  'denver co': 1014395,
  'colorado': 21139,
  'los angeles': 1013962,
  'new york': 1023191,
  'chicago': 1016367,
  'houston': 1026339,
  'phoenix': 1013211,
  'philadelphia': 1025197,
  'san antonio': 1025323,
  'san diego': 1014221,
  'dallas': 1026301,
  'austin': 1026481,
};

/**
 * Canada location codes (from existing fixmybrick tools)
 */
export const CANADA_LOCATION_CODES: Record<string, number> = {
  'canada': 2124,
  'ca': 2124,
  'toronto': 9061350,
  'hamilton': 9000414,
  'vancouver': 9061451,
  'montreal': 9061348,
  'calgary': 9061345,
  'edmonton': 9061346,
  'ottawa': 9061349,
};

/**
 * US state abbreviation to full name mapping
 * Used by formatLocationName() for Reviews API
 */
export const US_STATE_NAMES: Record<string, string> = {
  AL: 'Alabama', AK: 'Alaska', AZ: 'Arizona', AR: 'Arkansas', CA: 'California',
  CO: 'Colorado', CT: 'Connecticut', DE: 'Delaware', FL: 'Florida', GA: 'Georgia',
  HI: 'Hawaii', ID: 'Idaho', IL: 'Illinois', IN: 'Indiana', IA: 'Iowa',
  KS: 'Kansas', KY: 'Kentucky', LA: 'Louisiana', ME: 'Maine', MD: 'Maryland',
  MA: 'Massachusetts', MI: 'Michigan', MN: 'Minnesota', MS: 'Mississippi', MO: 'Missouri',
  MT: 'Montana', NE: 'Nebraska', NV: 'Nevada', NH: 'New Hampshire', NJ: 'New Jersey',
  NM: 'New Mexico', NY: 'New York', NC: 'North Carolina', ND: 'North Dakota', OH: 'Ohio',
  OK: 'Oklahoma', OR: 'Oregon', PA: 'Pennsylvania', RI: 'Rhode Island', SC: 'South Carolina',
  SD: 'South Dakota', TN: 'Tennessee', TX: 'Texas', UT: 'Utah', VT: 'Vermont',
  VA: 'Virginia', WA: 'Washington', WV: 'West Virginia', WI: 'Wisconsin', WY: 'Wyoming',
  DC: 'District of Columbia',
};

/**
 * Canadian province abbreviation to full name mapping
 * Used by formatLocationName() for Reviews API
 */
export const CANADA_PROVINCE_NAMES: Record<string, string> = {
  AB: 'Alberta',
  BC: 'British Columbia',
  MB: 'Manitoba',
  NB: 'New Brunswick',
  NL: 'Newfoundland and Labrador',
  NS: 'Nova Scotia',
  NT: 'Northwest Territories',
  NU: 'Nunavut',
  ON: 'Ontario',
  PE: 'Prince Edward Island',
  QC: 'Quebec',
  SK: 'Saskatchewan',
  YT: 'Yukon',
};

/**
 * Detect country based on state/province code.
 * Returns 'Canada' for Canadian provinces, otherwise returns provided country or 'USA'.
 */
export function detectCountry(state?: string, providedCountry?: string): string {
  if (state && CANADA_PROVINCE_NAMES[state.toUpperCase()]) {
    return 'Canada';
  }
  return providedCountry || 'USA';
}

/**
 * Country abbreviation to full name mapping
 */
export const COUNTRY_NAMES: Record<string, string> = {
  US: 'United States',
  USA: 'United States',
  CA: 'Canada',
  CAN: 'Canada',
};

/**
 * Format location for DataForSEO Reviews API
 *
 * The Reviews API requires location_name in "City,State,Country" format
 * with full names (not abbreviations).
 *
 * @example
 * formatLocationName('Denver', 'CO', 'USA') // => "Denver,Colorado,United States"
 * formatLocationName('Toronto', 'ON', 'CA') // => "Toronto,Ontario,Canada"
 * formatLocationName('Ottawa', 'ON', 'CA') // => "Ottawa,Ontario,Canada"
 */
export function formatLocationName(
  city: string,
  state?: string | null,
  country?: string | null
): string {
  const parts = [city];

  // Expand country abbreviations first (needed to determine which province mapping to use)
  const normalizedCountry = country?.toUpperCase() || 'USA';
  const fullCountry = COUNTRY_NAMES[normalizedCountry] || country || 'United States';
  const isCanada = fullCountry === 'Canada';

  if (state) {
    // Expand state/province abbreviations to full names based on country
    const stateUpper = state.toUpperCase();
    const fullState = isCanada
      ? CANADA_PROVINCE_NAMES[stateUpper] || state
      : US_STATE_NAMES[stateUpper] || state;
    parts.push(fullState);
  }

  parts.push(fullCountry);

  return parts.join(',');
}

/**
 * Resolve location string to DataForSEO location code
 *
 * IMPORTANT: For Google Maps API, city-specific codes don't work reliably.
 * Instead, use the national code (US: 2840, Canada: 2124) and include
 * the city name in the search keyword.
 */
export function resolveLocationCode(location: string): number {
  const normalized = location.toLowerCase().trim();

  // Check for Canada
  if (CANADA_LOCATION_CODES[normalized]) {
    // For Canada cities, use Canada national code
    // The city should be in the keyword instead
    return 2124;
  }

  // If it's explicitly a number, use it
  const num = parseInt(normalized, 10);
  if (!isNaN(num) && num > 1000) {
    return num;
  }

  // Default to US national for all US searches
  // City-specific codes don't work reliably with Google Maps API
  return 2840;
}
